version: "3.8"
services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      MONGO_URL: mongodb://admin:admin@mongo:27017/WishList
      NODE_ENV: production

  mongo:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: WishList
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
